### ISSUE TITLE
Asp.Net Core 2.2 Reference causing Mvc Analyzer errors

### ISSUE THREAD

**Issue by ComtelJeremy** [JonPSmith/EfCore.GenericServices.AspNetCore#4]
Hi Jon, thank you for your work with these libraries.
I was wondering if there is a reason you reference ASP.Net Core 2.2 and not > 2.2? With 2.2 references in a 3.1 project I am getting Analyzer errors (due to the Microsoft.AspNetCore.Mvc.Analyzers being referenced. Does it have to do with framework references? To get around this with a 3.1 project, is it best to simply duplicate your code in our project?

Perhaps I am missing something, I would very happy to hear your thoughts on this.

Error is like so:
`>CSC : warning AD0001: Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.`

**Comment by JonPSmith** [comment]
Hi @ComtelJeremy,

In some cases where I am using some basic types (in this case `ModelStateDictionary`) I tend to keep the lower version of the library. Sometimes this can cause problems, but loading the newer version of the offending library into your app sorts this out. Have you tried that.

Overall managing libraries for different versions of EF Core and ASP.NET Core has been a real pain. Once NET 5 is out I will align my libraries' version number to NET and take out the multi-target code in my libraries.

**Comment by ComtelJeremy** [comment]
I'm wondering if referencing the Mvc.Abstractions nuget would eliminate the problem (unless there is something in your code that needs an item not in the abstractions package). It might make your reference a little more specific, and not drag the Analyzer with it.

The Mvc package reference isn't being upgraded (I think because of framework references?). The code works, but it throws an error at build. I'll fork it and try and let you know.

I hear you about maintaining this with the version changes. Thanks again for your hard work, and I'll report back what I find, in case it is helpful to you.

**Comment by ComtelJeremy** [comment]
Hello Jon,

I spent a little time with this today. If you use the `Microsoft.AspNetCore.Mvc.Core` package, the Analyzers are not referenced, and your project builds correctly.

Also, wondering if there is a need to have the two Conditions for the TargetFrameworks in the csproj, since they both list the same packages.

Here is the csproj PackageReference portions I used:
```
<ItemGroup>
    <PackageReference Include="EfCore.GenericBizRunner" Version="4.1.0" />
    <PackageReference Include="EfCore.GenericServices" Version="3.1.0" />
    <PackageReference Include="GenericServices.StatusGeneric" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.1.1" />
  </ItemGroup>
```

Also, could this be an option? I just started using if for one of my internal libraries: [Docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-3.1&tabs=visual-studio#support-multiple-aspnet-core-versions) and would work around the entire issue of dragging an older version with your package.

Would a PR be welcome? I understand if not.

-Jeremy

**Comment by JonPSmith** [comment]
So, you are saying that you changed the library over to `Microsoft.AspNetCore.Mvc.Core` and that fixed your build - correct? Happy to change that.

I have already seen the docs you mention on multi-frameworks. That would work for this library but it won't work for my other libraries because they are often referenced from assemblies that use netstandard, and netstandard assemblies can't link to a netcoreapp assembly.

As I say, I will drop the multi-framework NuGet because a) it won't work in future because EF Core 2, 3, 5 all work with netstandard2.0, and b) its a pain write/debug multi-framework libraries.

**Comment by ComtelJeremy** [comment]
Yes. Changing to `Microsoft.AspNetCore.Mvc.Core` from `Microsoft.AspNetCore.Mvc` fixed the error, since the Analyzers are then not referenced. Thank you for considering the change.

I completely understand where you are coming from for the future plan, and I would likely do the same in your shoes. Thank you again for your help and always being so responsive to questions and issues.

**Comment by JonPSmith** [comment]
Ok. I will try an get this done next weekend.

**Comment by JonPSmith** [comment]
Just uploaded a version to NuGet using `Microsoft.AspNetCore.Mvc.Core`
